version: '3'

services:
  auth-environment:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: authentication_service
    ports:
      - '3307:3306'

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
